<a href="https://colab.research.google.com/github/srinivas340/ml_practice/blob/main/tensors%20and%20greadients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import torch

In [36]:
#number
t1=torch.tensor(4.)
t1

tensor(4.)

In [37]:
t1.dtype

torch.float32

In [38]:
#vector
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [39]:
#matrix
t3=torch.tensor([[[5.,6],[7,8],[9,10]]])
t3

tensor([[[ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]])

In [40]:
#3d array
t4=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,12]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [11, 12, 12]]])

In [41]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [42]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [43]:
print(t3)
t3.shape

tensor([[[ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]])


torch.Size([1, 3, 2])

In [44]:
print(t4)
t4.shape

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [11, 12, 12]]])


torch.Size([2, 2, 3])

**tensor operations and gradients**

In [45]:
#Create tensors.
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [46]:
#arithmetic operations
y= w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [47]:
#compute derivatives
y.backward()

the derivatives of y w.r.t the input tensors are stored in the (.grad) property of the respective tensors

In [48]:
#display gradients
print('dy/dx: ',x.grad)
print('dy/dw: ',w.grad)
print('dy/db: ',b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)
